### ISSUE TITLE
your_combine_mocks.py adding int and method types

### ISSUE THREAD

**Issue by ftorres-ucf** [thepetabyteproject/your#79] opened 2021-08-04 16:11 UTC
**Describe the bug**

The bug comes from running **your_combine_mocks.py** normally. 
Apparently the nsamp variable variable defined in line 303 is defined as a method instead of a number.

**To Reproduce**

This error was produced when running:
your_combine_mocks.py -f1 freq1/* -f2 freq2/*

The original files cannot be included since they are 2 files of 2GB size each
However this problem should be reproducable for any 2 frequency split file.

**Expected behavior**

I expected it to be able to combine both frequency files and not get stuck on line 308

**Screenshots**

![image](https://user-images.githubusercontent.com/83658048/128212797-27a948be-08df-447e-bfe2-cfadbe4ed346.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

-OS Centos8

**Additional context**

This should be fixed by changing line 303 from : 
nsamp = lowband_obj.nspectra
to:
nsamp = lowband_obj.nspectra()

**Comment by KshitijAggarwal** [comment] 2021-08-06 17:28
Thanks for pointing it out. your_combine_mocks.py needs a few other updates too. 
I will work on it in the week of 15th August. Feel free to submit a PR if you get a chance to fix it before that.

**Comment by KshitijAggarwal** [comment] 2021-08-15 17:37
I couldn't reproduce this error with the frequency split files I had, but I have made some changes in your_combine_mocks.py to fix some other errors. Can you try now, and confirm if you are still getting that error?

**Comment by ftorres-ucf** [comment] 2021-08-16 15:22
I am still getting this error, this time at line 342 when using the your_combine_mocks.py.

If I cahange lines 336 and 337 from:
if nsamp == -1:
        nsamp = lowband_obj.nspectra
to
if nsamp == -1:
        nsamp = lowband_obj.nspectra()

It is able to run. However, I do not know it this is the right fix for this.

My guess as to why you are not getting this error might be because the value of nsamp is getting set to something other than -1.

![image](https://user-images.githubusercontent.com/83658048/129587414-24db68ff-d69c-4f9f-aa2f-e0bd4decd667.png)

**Comment by ftorres-ucf** [comment] 2021-08-16 15:31
To trigger the error, you could use pdb to make a breakpoint before the nsamp condition, check the value, change it to -1, then run step by step until you reach the line 342.
Example:

python3 -m pdb your_combine_mocks.py -f1 Single_frequency_filename.fits -f2 Second_Single_frequency_filename.fits

#set breakpoint
b 336

#continue until breakpoint
c

#check for value of nsamp
pp nsamp

#change value to -1
nsamp = -1

#use next until error occurs
n

-----------
Hopefully this helps in recreating the error

**Comment by KshitijAggarwal** [comment] 2021-08-16 22:08
Fixed with 1cd7ebbb470e43daffe6a7b5d932d67159f25660. 
It was supposed to use nspectra in `your_header`, instead of the base one.

**Closed** 2021-08-31 17:05 UTC
Labels: bug, wontfix
